
       01  TELAFUNC.
           05  LINE 01  COLUMN 01 
               VALUE  " здддддддддддддддддддддддддддддддддддддд".
           05  LINE 01  COLUMN 41 
               VALUE  "дддддддддддддддддддддддддддддддд©".
           05  LINE 02  COLUMN 01 
               VALUE  " Ё                        CADASTRO DE FU".
           05  LINE 02  COLUMN 41 
               VALUE  "NCIONARIOS                      Ё".
           05  LINE 03  COLUMN 01 
               VALUE  " цдддддддддддддддддддддддддддддддддддддд".
           05  LINE 03  COLUMN 41 
               VALUE  "дддддддддддддддддддддддддддддддд╢".
           05  LINE 04  COLUMN 01 
               VALUE  " Ё CODIGO: 99999".
           05  LINE 04  COLUMN 41 
               VALUE  "                                Ё".
           05  LINE 05  COLUMN 01 
               VALUE  " цдддддддддддддддддддддддддддддддддддддд".
           05  LINE 05  COLUMN 41 
               VALUE  "дддддддддддддддддддддддддддддддд╢".
           05  LINE 06  COLUMN 01 
               VALUE  " Ё NOME: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX".
           05  LINE 06  COLUMN 41 
               VALUE  "XXXXX                           Ё".
           05  LINE 07  COLUMN 01 
               VALUE  " Ё CARTEIRA DE TRABALHO:".
           05  LINE 07  COLUMN 41 
               VALUE  "                                Ё".
           05  LINE 08  COLUMN 01 
               VALUE  " Ё     NUMERO: 99999  SERIE: 999  UF: XX".
           05  LINE 08  COLUMN 41 
               VALUE  "  XXXXXXXXXXXXXXXXXXXX          Ё".
           05  LINE 09  COLUMN 01 
               VALUE  " цдддддддддддддддддддддддддддддддддддддд".
           05  LINE 09  COLUMN 41 
               VALUE  "дддддддддддддддддддддддддддддддд╢".
           05  LINE 10  COLUMN 01 
               VALUE  " Ё CPF: 999999999-99".
           05  LINE 10  COLUMN 41 
               VALUE  "   DATA DE NASC: 99/99/9999     Ё".
           05  LINE 11  COLUMN 01 
               VALUE  " Ё TELEFONE: (99) 999999999       EMAIL:".
           05  LINE 11  COLUMN 41 
               VALUE  " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Ё".
           05  LINE 12  COLUMN 01 
               VALUE  " цдддддддддддддддддддддддддддддддддддддд".
           05  LINE 12  COLUMN 41 
               VALUE  "дддддддддддддддддддддддддддддддд╢".
           05  LINE 13  COLUMN 01 
               VALUE  " Ё SEXO: X XXXXXXXXXXXXX          OP─AO".
           05  LINE 13  COLUMN 41 
               VALUE  "SEXUAL: 9 XXXXXXXXXXXXXXXXXXXXX Ё".
           05  LINE 14  COLUMN 01 
               VALUE  " юдддддддддддддддддддддддддддддддддддддд".
           05  LINE 14  COLUMN 41 
               VALUE  "дддддддддддддддддддддддддддддддды".
